#!/usr/bin/env python

import sys
import argparse
import subprocess


def main(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument("task", help="The invoke task to run")
    parser.add_argument("files", nargs='*')

    args, unknown_arguments = parser.parse_known_args(args=argv)
    command = ["invoke", args.task]
    if unknown_arguments:
        command.extend(unknown_arguments)
    if args.files:
        command.extend([
            "--files",
            " ".join(fname.strip() for fname in args.files)
        ])
    ret = subprocess.run(command, shell=False, check=False)
    if ret.returncode:
        parser.exit(status=1)
    parser.exit(status=0)


if __name__ == "__main__":
    main(sys.argv[1:])
